services:
  application:
    image: ${IMAGE_NAME}
    container_name: testdockerashwini.azurecr.io
    ports:
      - "8080:8080"
    environment:
      - ACR_REGISTRY_USERNAME=${ACR_REGISTRY_USERNAME}
      - ACR_REGISTRY_PASSWORD=${ACR_REGISTRY_PASSWORD}
      - ACR_REGISTRY_NAME=${ACR_REGISTRY_NAME}
      - ACR_REGISTRY_LOGIN_SERVER=${ACR_REGISTRY_LOGIN_SERVER}
      - AZURE_WEBAPP_NAME=${AZURE_WEBAPP_NAME}
      - AZURE_RESOURCE_GROUP=${AZURE_RESOURCE_GROUP}
      - MONGO_DB_URL=${MONGO_DB_URL}
