version: "2"
services:
 application:
    image: ${IMAGE_NAME}
    container_name: testdockerashwini.azurecr.io
    ports:
      - "8080:8080"
    environment:
      - AZURE_User_name=${AZURE_User_name}
      - AZURE_Password=${AZURE_Password}
      - AZURE_Service_Publish_Profile=${AZURE_Service_Publish_Profile}
      - MONGO_DB_URL=${MONGO_DB_URL}