version: "2"
services:
 application:
    image: ${IMAGE_NAME}
    container_name: shipping_prediction
    ports:
      - "8080:8080"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - MONGO_DB_URL=${MONGO_DB_URL}
      - AWS_REGION=${AWS_REGION}
      - ECR_REPOSITORY_NAME=${ECR_REPOSITORY_NAME}
      - AWS_ECR_LOGIN_URI=${AWS_ECR_LOGIN_URI}