name: Azure CI/CD for Consignment Shipping Price Prediction

on:
  workflow_run:
    workflows: ["Azure CI/CD for Consignment Shipping Price Prediction"]
    types:
      - completed

jobs:
  self-hosted-runner:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-action@v2

      - name: Log in to Azure Container Registry
        run: |
          docker login ${{ secrets.ACR_REGISTRY_LOGIN_SERVER }} -u ${{ secrets.ACR_REGISTRY_USERNAME }} -p ${{ secrets.ACR_REGISTRY_PASSWORD }}

      - name: Pull Docker image
        run: docker pull ${{ secrets.ACR_REGISTRY_LOGIN_SERVER }}/shipping_prediction:latest

      - name: Deploy Docker Compose
        run: |
          export IMAGE_NAME="${{ secrets.ACR_REGISTRY_LOGIN_SERVER }}/shipping_prediction:latest"
          docker-compose -f docker-compose.yaml up -d

      - name: Docker System Prune to Remove Old Images
        run: docker system prune -f
