name: workflow

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push-azure-image:
    name: Continuous Delivery
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Utilities
        run: |
          sudo apt-get update
          sudo apt-get install -y jq unzip

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v1
        with:
          registry: https://testdockerashwini.azurecr.io/
          username: ${{ secrets.AZURE_User_name }}
          password: ${{ secrets.AZURE_Password }}

      - name: Build and push container image
        run: |
          docker build -t testdockerashwini.azurecr.io/shipping_prediction:latest .
          docker push testdockerashwini.azurecr.io/shipping_prediction:latest

  Continuous-Deployment:
    needs: build-and-push-azure-image
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to Azure Container Registry
        run: docker login testdockerashwini.azurecr.io -u ${{ secrets.AZURE_User_name }} -p ${{ secrets.AZURE_Password }}

      - name: Pull Docker image
        run: docker pull testdockerashwini.azurecr.io/shipping_prediction:latest

      - name: Run Docker Image
        run: |
        export IMAGE_NAME="testdockerashwini.azurecr.io/shipping_prediction:latest"
        docker-compose up -d


      - name: Docker System Prune to Remove Old Images
        run: |
          docker system prune -f
